name: dash_trials_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python==3.8.5
  - pip==20.2.2
  # Development environment
  - jupyter==1.0.0
  - jupyterlab==2.2.6
  - notebook==6.1.3
  - ipython==7.18.1
  - ipykernel==5.3.4
  - jupytext==1.6.0
  - pyprojroot==0.2.0
  - pylint==2.6.8
  # Code dependencies
  - numpy==1.19.1
  - pandas==1.1.1
  - plotly==4.9.0
  - dash==1.14.0
  # - jupyter-dash  # TODO: Try this out
  # - dash-bootstrap-components  # TODO: Try this out
